#!/bin/bash
export MY_JOB_NAME='1206_1934_ALGO_PERFORMANCE_FUTURE_PAPER_500M_SHORTCUTS'
export MY_MEMORY_PER_CPU='30000MB'
export MY_MINUTES_PER_RUN=240
export MY_PRIORITY=NORMAL
export MY_NODE_TYPE='CPU_ONLY'
export MY_CPU_PER_RUN=1
